package com.example.tripplan.model

data class ItemXX(
    val accomcountlodging: String,
    val barbecue: String,
    val beauty: String,
    val benikia: String,
    val beverage: String,
    val bicycle: String,
    val campfire: String,
    val checkintime: String,
    val checkouttime: String,
    val chkcooking: String,
    val contentid: String,
    val contenttypeid: String,
    val fitness: String,
    val foodplace: String,
    val goodstay: String,
    val hanok: String,
    val infocenterlodging: String,
    val karaoke: String,
    val parkinglodging: String,
    val pickup: String,
    val publicbath: String,
    val publicpc: String,
    val refundregulation: String,
    val reservationlodging: String,
    val reservationurl: String,
    val roomcount: String,
    val roomtype: String,
    val sauna: String,
    val scalelodging: String,
    val seminar: String,
    val sports: String,
    val subfacility: String
)